name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    name: Docs
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.DOCS_TOKEN }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup docfx
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: docs~
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.DOCS_TOKEN }}

      - name: Generate metadata
        working-directory: docs~
        run: npm run-script docfx

      - name: Build docs
        working-directory: docs~
        run: npm build
        continue-on-error: false

      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DOCS_TOKEN }}
          external_repository: zigurous/docs
          destination_dir: com.zigurous.animation
          publish_dir: docs~/public
          publish_branch: main
