name: Generate Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PACKAGE_BASE_PATH: com.zigurous.animation
  PACKAGE_TITLE: "Animation Library"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout package
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DOCS_TOKEN }}

      - name: Checkout docs template
        uses: actions/checkout@v3
        with:
          repository: zigurous/docs-template
          ref: unity-package
          token: ${{ secrets.DOCS_TOKEN }}
          path: docs~

      - name: Build docs
        uses: ./docs~/.github/actions/build-docs
        with:
          npm_token: ${{ secrets.DOCS_TOKEN }}
          package_base_path: ${{ env.PACKAGE_BASE_PATH }}
          package_title: ${{ env.PACKAGE_TITLE }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs~/public

  publish:
    name: Publish
    needs: build
    runs-on: windows-latest
    steps:
      - name: Dispatch workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DOCS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'zigurous',
              repo: 'docs',
              ref: 'main',
              workflow_id: 'publish_artifact.yml',
              inputs: {
                destination_path: process.env.BASE_PATH,
                artifact_repo: process.env.GITHUB_REPOSITORY,
                artifact_commit: process.env.GITHUB_SHA,
                artifact_workflow: 'generate_docs.yml',
                artifact_name: 'docs'
              }
            })
