name: Generate docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  generate-docs:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx

      - name: Install dependencies
        run: dotnet restore
      
      - name: DocFX Build
        working-directory: .docfx
        run: docfx docfx.json
        continue-on-error: false
        
      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .docfx/dist
          publish_branch: docs
          force_orphan: true
