name: Generate Docs

on:
  push:
    branches:
      - main

env:
  BASE_PATH: com.zigurous.animation
  PACKAGE_TITLE: "Animation Library"

jobs:
  generate:
    name: Generate Docs
    runs-on: windows-latest
    steps:
      - name: Checkout package
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DOCS_TOKEN }}

      - name: Checkout docs template
        uses: actions/checkout@v3
        with:
          repository: zigurous/docs-template
          ref: unity-package
          token: ${{ secrets.DOCS_TOKEN }}
          path: docs~

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup docfx
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: docs~
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.DOCS_TOKEN }}

      - name: Generate documentation
        working-directory: docs~
        run: npm run-script generate $env:BASE_PATH $env:PACKAGE_TITLE
        env:
          NPM_TOKEN: ${{ secrets.DOCS_TOKEN }}

      - name: Build docs
        working-directory: docs~
        continue-on-error: false
        run: npm run-script build
        env:
          NPM_TOKEN: ${{ secrets.DOCS_TOKEN }}

      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DOCS_TOKEN }}
          external_repository: zigurous/docs
          destination_dir: ${{ env.BASE_PATH }}
          publish_dir: docs~/public
          publish_branch: main
