name: Merge Branch

on:
  push:
    branches:
      - main

jobs:
  merge-branch:
    name: Merge Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.DOCS_TOKEN }}
          source_ref: 'main'
          target_branch: 'docs'
          commit_message_template: '[Automated] Merge {source_ref} into {target_branch}'
